<?php

namespace Haswalt\SecurityBundle\Repository;

use Haswalt\ApiBundle\Doctrine\ORM\PaginatedRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends PaginatedRepository
{
    public function checkAvailability($username)
    {
        $qb = $this->createQueryBuilder('u');
        $query = $qb->select($qb->expr()->count('u.username'))
            ->where($qb->expr()->eq('u.username', ':username'))
            ->setParameter('username', $username)
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleScalarResult() == 0;
    }
}
